import { useState } from "react";
import { ArrowRight, Compass, HardHat, ShieldCheck, Target } from "lucide-react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { PageLayout } from "@/components/PageLayout";

const milestones = [["01", "Foundation", "[Milestone year]", "JMV begins with a commitment to dependable engineering and accountable execution."], ["02", "Capability", "[Milestone year]", "[Verified capability milestone] expands the company's infrastructure delivery scope."], ["03", "Regional reach", "[Milestone year]", "[Verified regional milestone] strengthens support for projects across key corridors."], ["04", "Next chapter", "Today", "Continuing to build practical capacity for India's next generation of infrastructure."]];
export const Route = createFileRoute("/about")({ head: () => ({ meta: [{ title: "About | JMV Engineering Infra" }] }), component: AboutPage });
function AboutPage() {
  const [active, setActive] = useState(0);
  const policies = [[Compass, "Vision", "To be a trusted infrastructure partner known for engineering clarity, responsible delivery, and work that performs for the long term."], [Target, "Mission", "To deliver quality construction and infrastructure solutions through capable people, disciplined processes, and transparent collaboration."], [HardHat, "Safety policy", "Safety is a daily operating responsibility. We plan work carefully, communicate risks, and protect everyone affected by our sites."], [ShieldCheck, "Quality assurance", "We build quality into planning, procurement, execution, inspection, and handover, with verification kept visible at every stage."]] as const;
  return <PageLayout eyebrow="About JMV" title="Built on engineering discipline and trusted execution." description="JMV Engineering Infra works across public, civic, and strategic infrastructure projects with a focus on reliability, safety, and long-term performance."><section className="rounded-[2rem] bg-jmv-brown p-8 text-white md:p-10"><p className="eyebrow text-jmv-orange">Our story</p><div className="mt-8 grid gap-10 lg:grid-cols-[0.7fr_1.3fr]"><div className="flex gap-3 overflow-x-auto pb-2 lg:block lg:space-y-3">{milestones.map(([number, title], index) => <button key={number} type="button" onClick={() => setActive(index)} className={`min-w-[8rem] rounded-xl border p-4 text-left lg:block lg:w-full ${active === index ? "border-jmv-orange bg-jmv-orange" : "border-white/15 bg-white/5 text-white/65"}`}><span className="text-xs font-bold">{number}</span><span className="mt-3 block font-semibold">{title}</span></button>)}</div><div className="flex min-h-48 flex-col justify-end"><p className="eyebrow text-jmv-orange">{milestones[active][2]}</p><h2 className="mt-4 text-3xl font-bold text-white md:text-4xl">{milestones[active][1]}</h2><p className="mt-5 max-w-xl text-base leading-8 text-white/70">{milestones[active][3]}</p></div></div></section><section className="mt-16 grid gap-5 md:grid-cols-2">{policies.map(([Icon, title, copy]) => <article key={title} className="rounded-2xl border border-border bg-white p-7 shadow-soft"><Icon className="h-6 w-6 text-jmv-orange" /><h2 className="mt-6 text-2xl font-bold text-jmv-brown">{title}</h2><p className="mt-4 text-sm leading-7 text-jmv-charcoal/70">{copy}</p></article>)}</section><section className="mt-16 flex flex-col gap-6 rounded-[2rem] bg-jmv-grey p-8 md:flex-row md:items-center md:justify-between md:p-10"><div><p className="eyebrow text-jmv-orange">Meet the team</p><h2 className="mt-3 text-3xl font-bold text-jmv-brown">People, capability, and responsibility behind every delivery.</h2></div><Link to="/people" className="inline-flex items-center gap-2 self-start rounded-full bg-jmv-orange px-5 py-3 text-sm font-semibold text-white">Leadership <ArrowRight className="h-4 w-4" /></Link></section></PageLayout>;
}
