import { useState } from "react";
import { X } from "lucide-react";
import { createFileRoute } from "@tanstack/react-router";
import { PageLayout } from "@/components/PageLayout";

type Person = { name: string; role: string; bio: string };
const leaders: Person[] = [{ name: "[Director Name]", role: "Director, Strategy & Delivery", bio: "[Verified leadership biography] Focused on project governance, client relationships, and long-term infrastructure partnerships." }, { name: "[Project Head Name]", role: "Project Head, Civil Infrastructure", bio: "[Verified leadership biography] Leads planning, site coordination, and execution controls across infrastructure packages." }, { name: "[Engineering Lead Name]", role: "Head of Engineering & Planning", bio: "[Verified leadership biography] Connects technical planning, constructability, and field-ready delivery methods." }, { name: "[QA / HSE Lead Name]", role: "Head of Quality & Safety", bio: "[Verified leadership biography] Owns quality assurance, safety systems, and continuous improvement on site." }];
export const Route = createFileRoute("/people")({ head: () => ({ meta: [{ title: "Leadership | JMV Engineering Infra" }] }), component: PeoplePage });
function PeoplePage() { const [selected, setSelected] = useState<Person | null>(null); return <PageLayout eyebrow="Founders & leadership" title="Experienced people shaping dependable project outcomes." description="JMV brings together strategic leadership, engineering judgment, and practical site understanding to deliver infrastructure with accountability."><section className="grid gap-10 rounded-[2rem] bg-jmv-brown p-8 text-white md:p-12 lg:grid-cols-[0.8fr_1.2fr]"><div className="flex min-h-64 items-end rounded-2xl border border-white/10 bg-white/5 p-6"><p className="text-6xl font-extrabold tracking-[-0.08em] text-jmv-orange/80">JMV</p></div><div><p className="eyebrow text-jmv-orange">Founder spotlight</p><h2 className="mt-4 text-4xl font-bold text-white">[Founder Name]</h2><p className="mt-6 text-lg leading-8 text-white/75">“[Vision Message]”</p><div className="mt-8 grid gap-5 border-t border-white/15 pt-6 sm:grid-cols-2"><div><p className="eyebrow text-white/50">Industry focus</p><p className="mt-2 text-sm leading-7 text-white/75">[Verified Industry Focus]</p></div><div><p className="eyebrow text-white/50">Profile</p><p className="mt-2 text-sm leading-7 text-white/75">[Founder Profile Placeholder]</p></div></div></div></section><section className="mt-16"><p className="eyebrow text-jmv-orange">Executive leadership</p><h2 className="mt-3 text-3xl font-bold text-jmv-brown">The people responsible for moving work forward.</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{leaders.map((person, index) => <button key={person.name} type="button" onClick={() => setSelected(person)} className="rounded-2xl border border-border bg-white p-6 text-left shadow-soft hover:-translate-y-1 hover:border-jmv-orange/50"><div className="flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-jmv-orange text-lg font-bold text-white">0{index + 1}</span><div><h3 className="font-bold text-jmv-brown">{person.name}</h3><p className="mt-1 text-sm text-jmv-charcoal/65">{person.role}</p></div></div><p className="mt-5 text-xs font-semibold uppercase tracking-[0.12em] text-jmv-orange">View profile</p></button>)}</div></section>{selected ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-jmv-brown/80 p-6" role="dialog" aria-modal="true" aria-label={`${selected.name} profile`}><div className="relative w-full max-w-lg rounded-2xl bg-white p-8"><button type="button" onClick={() => setSelected(null)} className="absolute right-5 top-5 rounded-full bg-jmv-grey p-2 text-jmv-brown" aria-label="Close profile"><X className="h-5 w-5" /></button><p className="eyebrow text-jmv-orange">Leadership profile</p><h2 className="mt-4 text-3xl font-bold text-jmv-brown">{selected.name}</h2><p className="mt-2 text-sm font-semibold text-jmv-orange">{selected.role}</p><p className="mt-6 text-base leading-8 text-jmv-charcoal/70">{selected.bio}</p></div></div> : null}</PageLayout>; }
